trainingInput:
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: "fitness_score"
    maxTrials: 1000
    maxParallelTrials: 10
    enableTrialEarlyStopping: True
    params:
    - parameterName: ProbabilityOfSwitchingToSearching
      type: DOUBLE
      minValue: 0.0
      maxValue: 1.0
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: ProbabilityOfReturningToNest
      type: DOUBLE
      minValue: 0.0
      maxValue: 1.0
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: UninformedSearchVariation
      type: DOUBLE
      minValue: 0.0
      maxValue: 12.56637
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: RateOfInformedSearchDecay
      type: DOUBLE
      minValue: 0.0
      maxValue: 148.41315
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: RateOfSiteFidelity
      type: DOUBLE
      minValue: 0.0
      maxValue: 20.0
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: RateOfLayingPheromone
      type: DOUBLE
      minValue: 0.0
      maxValue: 20.0
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: RateOfPheromoneDecay
      type: DOUBLE
      minValue: 0.0
      maxValue: 22026.46579
      scaleType: UNIT_LINEAR_SCALE